//const para PROYECTOS
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const INPUT_PROYECTO = 'INPUT_PROYECTO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const ERROR_PROYECTO = 'ERROR_PROYECTO';
export const SET_ALLPROYECTOS = 'SET_ALLPROYECTOS';

//const para TAREAS
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const INPUT_TAREA = 'INPUT_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const LIMPIAR_TAREA = 'LIMPIAR_TAREA';
export const SET_ALLTAREAS = 'SET_ALLTAREAS';

//Const para ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRARALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//const para AUTH
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';